### ISSUE TITLE
Problème adresses sur Roubaix - 59512

### ISSUE THREAD

**Issue by cquest** [osm-fr/export-cadastre#15]
Traceback (most recent call last):
  File "/data/project/cadastre.openstreetmap.fr/export-cadastre/bin/cadastre-housenumber/bano/cadastre_vers_osm_adresses_pour_bano.py", line 1037, in cadastre_vers_adresses
    cherche_fantoir_et_osm_highways(code_departement, code_commune, osm, osm_noms)
  File "/data/project/cadastre.openstreetmap.fr/export-cadastre/bin/cadastre-housenumber/bano/cherche_fantoir_et_osm_highways.py", line 338, in cherche_fantoir_et_osm_highways
    if r.tags.get('type') == 'associatedStreet'])
  File "/data/project/cadastre.openstreetmap.fr/export-cadastre/bin/cadastre-housenumber/bano/cherche_fantoir_et_osm_highways.py", line 72, in normalize
    result = addr_fantoir_building.normalize(to_ascii(nom))
  File "/data/project/cadastre.openstreetmap.fr/export-cadastre/bin/cadastre-housenumber/bano/associatedStreet/addr_fantoir_building.py", line 190, in normalize
    if sp[-1] in dicts.chiffres_romains:
IndexError: list index out of range

**Comment by sletuffe** [comment]
testé à l'instant, si on met de coté le fait que ça prend 2000 secondes, ça marche sans l'erreur citée
