### ISSUE TITLE
Crash lors de la génération du bâti pour une petite zone

### ISSUE THREAD

**Issue by bagage** [osm-fr/export-cadastre#26]
Pour la bbox suivante [ici](https://www.openstreetmap.org/#map=17/43.85719/4.43638) : 

![image](https://user-images.githubusercontent.com/1451988/35818853-675529de-0aa1-11e8-8044-d8740b4e5466.png)

```
Teléchargement des PDFs de la commune E0189 : NIMES (30900)
Découpe la bbox en 3 * 2 [6 pdfs]
E0189-0-0.pdf
Parse les exports PDF du cadastre:
E0189-0-0.pdf: 0 buildings, 0 light buildings, 0 water, 0 riverbank, 1 limit
Traceback (most recent call last):
  File "/data/project/cadastre.openstreetmap.fr/bin/cadastre-housenumber/bin/osm_houses_simplify.py", line 78, in 
    sys.exit(main(sys.argv))
  File "/data/project/cadastre.openstreetmap.fr/bin/cadastre-housenumber/bin/osm_houses_simplify.py", line 72, in main
    simplify(osm_data, merge_distance, join_distance, simplify_threshold)
  File "/data/project/cadastre.openstreetmap.fr/export-cadastre/bin/cadastre-housenumber/cadastre_fr/simplify.py", line 45, in simplify
    inputTransform, outputTransform = get_centered_metric_equirectangular_transformation_from_osm(osm_data)
  File "/data/project/cadastre.openstreetmap.fr/export-cadastre/bin/cadastre-housenumber/cadastre_fr/transform.py", line 124, in get_centered_metric_equirectangular_transformation_from_osm
    bbox = BoundingBox(*osm_data.bbox())
TypeError: type object argument after * must be a sequence, not NoneType

```

**Comment by bagage** [comment]
Use `./bin/import-ville2.sh 030 E0189 NIMES 4.43093,43.85996,4.44778,43.85348` to reproduce.

**Comment by bagage** [comment]
edit: en fait c'est dû au fait que la bounding box ne fait pas partie de Nîmes 🤦‍♂️ . 
Bon au lieu du crash, un message d'erreur serait plus sympa ;)
