### ISSUE TITLE
OSError: [Errno 13] Permission denied: 'parcelles_adresses'

### ISSUE THREAD

**Issue by pamputt** [osm-fr/export-cadastre#40]
En voulant générer des adresses pour la ville d'Anzin (59014), à la fin de la génération j'obtiens l'erreur suivante 
```
Traceback (most recent call last):
  File "addr_fantoir_building.py", line 892, in 
    main(sys.argv)
  File "addr_fantoir_building.py", line 659, in main
    os.mkdir(rep_parcelles_adresses)
OSError: [Errno 13] Permission denied: 'parcelles_adresses'
```
Un certain nombre de fichiers n'ont pas été générés (NR014-ANZIN-adresses-addrstreet_point_sur_batiment.zip, NR014-ANZIN-adresses-addrstreet_tag_sur_batiment.zip, NR014-ANZIN-adresses-associatedStreet_point_sur_batiment.zip, NR014-ANZIN-adresses-associatedStreet_tag_sur_batiment.zip).

**Comment by vdct** [comment]
Bonjour,
le service en question n'est plus maintenu et sera prochainement fermé. Un autre service propose la même granularité : des adresses par rue par commune. C'est ici pour Anzin :
http://dev.cadastre.openstreetmap.fr/fantoir/#insee=59014&tab=0
